name: Build and test develop

on:
 push:
   branches: [ develop ]
 pull_request:
   branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true


    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build LINQAnalyzer
      run: dotnet build --no-restore LINQAnalyzer
    - name: Build LINQAnalyzer.CodeFixes
      run: dotnet build --no-restore LINQAnalyzer.CodeFixes
        
    
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
