name: Build and test develop

on:
 push:
   branches: [ develop ]
 pull_request:
   branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true

    strategy:
      fail-fast: true
      matrix:
        project: [ LINQAnalyzer, LINQAnalyzer.CodeFixes ]


    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ matrix.project }}
    - name: Build
      run: dotnet build --no-restore ${{ matrix.project }}
        
    
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
